---
galaxy_info:
  author: Pieter Lexis
  description: PowerDNS Authoritative Server role
  company: PowerDNS.COM BV
  license: GPLv2
  min_ansible_version: 0.9
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Debian
    versions:
    - jessie
  categories:
  - system
dependencies: []
